//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRoute
    {
        public int IDAccountRoute { get; set; }
        public int RouteID { get; set; }
        public int AccountID { get; set; }
        public string RouteType { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Route Route { get; set; }
    }
}
