//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IG_DB_Entities : DbContext
    {
        public IG_DB_Entities()
            : base("name=IG_DB_Entities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountRoute> AccountRoutes { get; set; }
        public virtual DbSet<Bar> Bars { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Monument> Monuments { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteBar> RouteBars { get; set; }
        public virtual DbSet<RouteMonument> RouteMonuments { get; set; }
        public virtual DbSet<RouteRestaurant> RouteRestaurants { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
